# site metadata
site_name: Incinerator firmware docs
site_author: Patrick Huesmann
repo_name: cadus/incinerator
repo_url: https://github.com/cadus/incinerator

# theme settings
theme: readthedocs

# enable mermaid
# (pip3 install mkdocs-mermaid2-plugin)
plugins:
    - search
    - mermaid2:

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

# navigation
nav:
    - 'Introduction': 'index.md'
    - 'User interface': 'ui.md'
    - 'Incinerator': 'incinerator.md'
    - 'Burn chamber': 'burn_chamber.md'
    - 'Ignition': 'ignition.md'
    - 'Serial control': 'serial_ctrl.md'
    - 'PCB': 'pcb.md'

extra_css:
    - extra.css
