#pragma once

#include <stdint.h>
#include "icon.h"

// Auto-generated by scripts/create_icons.sh - do not edit

extern const Icon icon_box_clear;
extern const Icon icon_box_filled;
extern const Icon icon_clock;
extern const Icon icon_flame;
extern const Icon icon_snowflake;
extern const Icon icon_thermometer;
