#pragma once

#include <stdint.h>

// Auto-generated by scripts/create_icons.sh - do not edit

#define ICON_BOX_CLEAR_WIDTH 16
#define ICON_BOX_CLEAR_HEIGHT 16
extern const uint8_t ICON_BOX_CLEAR_DATA[];

#define ICON_BOX_FILLED_WIDTH 16
#define ICON_BOX_FILLED_HEIGHT 16
extern const uint8_t ICON_BOX_FILLED_DATA[];

#define ICON_CLOCK_WIDTH 33
#define ICON_CLOCK_HEIGHT 40
extern const uint8_t ICON_CLOCK_DATA[];

#define ICON_FLAME_WIDTH 33
#define ICON_FLAME_HEIGHT 40
extern const uint8_t ICON_FLAME_DATA[];

#define ICON_THERMOMETER_WIDTH 31
#define ICON_THERMOMETER_HEIGHT 40
extern const uint8_t ICON_THERMOMETER_DATA[];

