#!/bin/bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
projDir="${scriptDir}/../"

incFile="${projDir}/include/icons.h"
srcFile="${projDir}/src/icons.cpp"

cat > "${incFile}" <<EOF
#pragma once

#include <stdint.h>

EOF

cat > "${srcFile}" <<EOF
#include "icons.h"
#include <stdint.h>

EOF

AUTO_GEN_COMMENT="// Auto-generated by $0 - do not edit\n\n"

echo -en "${AUTO_GEN_COMMENT}" >> "${incFile}"
echo -en "${AUTO_GEN_COMMENT}" >> "${srcFile}"

#${scriptDir}/icon2cpp.py "${projDir}/icons/test.svg" -w 32 -s "${srcFile}" -i "${incFile}"
${scriptDir}/icon2cpp.py "${projDir}/icons/box_clear.png" -s "${srcFile}" -i "${incFile}"
${scriptDir}/icon2cpp.py "${projDir}/icons/box_filled.png" -s "${srcFile}" -i "${incFile}"
